version: '3'
services:
  banco_digital_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: banco_digital/v1
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=docker
    links:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./BANCO_MYSQL.sql:/docker-entrypoint-initdb.d/init.sql
